[build-system]
requires = [
    "setuptools >= 77.0.3",
    "setuptools-scm[simple]>=9.2",
]
build-backend = "setuptools.build_meta"

[project]
name = "gamse"
dynamic = ["version"]
authors = [
  { name="Liang Wang", email="wang.leon@gmail.com" },
]
description = "Generic Echelle Data Reduction Package"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = { text = "Apache-2.0" }
dependencies = [
    "numpy>=1.24",
    "scipy>=1.8.0",
    "matplotlib>=3.4.1",
    "astropy>=5.1",
    "scikit-learn>=1.1.2",
    "PyYAML>=6.0",
]

[project.urls]
Homepage = "https://github.com/wangleon/gamse"
Issues = "https://github.com/wangleon/gamse/issues"
