[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "gamse"
version = "0.98"
authors = [
  { name="Liang Wang", email="wang.leon@gmail.com" },
]
description = "Generic Echelle Data Reduction Package"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = { text = "Apache-2.0" }

[project.urls]
Homepage = "https://github.com/wangleon/gamse"
Issues = "https://github.com/wangleon/gamse/issues"
