#!/usr/bin/env python3
import os
import sys

from gamse.pipelines import (make_config, make_obslog, reduce_echelle,
                             plot_spectra1d, show_onedspec, convert_onedspec)

def print_help():
    pass

def main():

    if len(sys.argv)==1:
        print_help()
        exit()

    command = sys.argv[1]

    if command == 'config':
        make_config()
    elif command == 'list':
        # list the observing log of raw data
        make_obslog()
    elif command == 'reduce':
        # reduce the spectra
        reduce_echelle()
    elif command == 'plot':
        plot_spectra1d()
    elif command == 'show':
        show_onedspec()
    elif command == 'convert':
        convert_onedspec()
    else:
        print('Unknow command: {}'.format(command))
        exit()

if __name__=='__main__':
    main()
